### ISSUE TITLE
Corporate Design issues and suggestions

### ISSUE THREAD

**Issue by capi3** [EnormousCloud/api3-dao-tracker#11]
Navigation
- set bg to #030303
- set active menu point and bottom border to #F3F3F3
- set hover color for the line and typo to #7CE3CB
- replace box shadow with a white line	

Body
- set bg to #030303
- add more space at the top 
- replace error color #FFC0CB by #E83151
- set color of H1 and H2 to #F3F3F3

Wallets
- set „withdrawn“ tag to #E83151

Votings
- set Primary tag to #7CE3CB
- set secoundary tag to  #D233F2
- set „InvalidTransfer“ tag to #E83151

**Comment by EnormousCloud** [comment]
Thanks for the feedback
The changes were applied and published.
