### ISSUE TITLE
ENS and balance issues

### ISSUE THREAD

**Issue by Midhav** [EnormousCloud/api3-dao-tracker#7]
I'm not sure if this is an issue because you'd pointed out in the forums that it takes 1-2 days for the registry to be re-read, but my address midhav.eth has not appeared in the wallet tracker yet. 
I'd done the reverse address record a couple of days ago and staked about 2 days ago.
Another issue I've noticed is that another address which undelegated recently has had its staked amount appear as zero: https://enormous.cloud/dao/api3/tracker/wallets/0xce6210888560fb210f20acf683a2989619a1f4fb

**Comment by EnormousCloud** [comment]
> I'm not sure if this is an issue because you'd pointed out in the forums that it takes 1-2 days for the registry to be re-read, but my address midhav.eth has not appeared in the wallet tracker yet.
> I'd done the reverse address record a couple of days ago and staked about 2 days ago.

Thanks for reminding. Indeed ENS records are checked manually when I restart a tool.
I will close this ticket once the ENS re-checks will be done once an hour - this will happen this week.

Your name is fine now and you can see yourself. Welcome to the staking pool.

> Another issue I've noticed is that another address which undelegated recently has had its staked amount appear as zero: https://enormous.cloud/dao/api3/tracker/wallets/0xce6210888560fb210f20acf683a2989619a1f4fb

I checked ethercan and see no issue here. This wallet moved all of its funds 47 days 20 hrs ago
to this address: https://enormous.cloud/dao/api3/tracker/wallets/0x439a2d8c08751ad4e8130c2585c7108fd3957f0c
and that one was the wallet with delegation to Erich.

Mentioned wallet never had any actual interaction with the staking pool, and it appeared in the tracker as one of the addresses that are announced as vested. I am not sure of what kind of vesting was that :)

**Comment by Midhav** [comment]
Thanks for the response and for adding me in there!
